reportStatus: true
deleteBranchAfterMerge: true

# must be enabled as a merge option in the repository settings
mergeMethod: squash
blockingLabels:
- blocked

rules:
- requiredAuthorRole: app/dependabot
  minApprovals:
    NONE: 0
- minApprovals:
   MEMBER: 1
