version: '{build}'
image: Visual Studio 2022

skip_branch_with_pr: true

environment:
  NUGET_XMLDOC_MODE: skip
  DOTNET_CLI_TELEMETRY_OPTOUT: 1

branches:
  only:
    - master

build_script:
- cmd: ./build.cmd

test: off
deploy: off
